In [91]:
import pandas as pd

In [92]:
#TO Import sales data (csv file) into the notebook

sales_data=pd.read_csv('sales_data.csv')

In [93]:
len(sales_data)

710

In [108]:
#Data cleaning

In [94]:
#To drop duplicates in the sales dataset

sales_data.drop_duplicates()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3.0,20.0,32370.0,32370.00,16185.0,16185.00,01/01/2019,1.0,Jan,2019.0
1,Government,GERMANY,Carretera,NaN,1321.0,3.0,20.0,26420.0,26420.00,13210.0,13210.00,01/01/2019,1.0,Jan,2019.0
2,Midmarket,France,Carretera,NaN,2178.0,3.0,15.0,32670.0,32670.00,21780.0,10890.00,01/06/2019,6.0,Jun,2019.0
3,Midmarket,GERMANY,Carretera,NaN,888.0,3.0,15.0,13320.0,13320.00,8880.0,4440.00,01/06/2019,6.0,Jun,2019.0
4,Midmarket,Mexico,Carretera,NaN,2470.0,3.0,15.0,37050.0,37050.00,24700.0,12350.00,01/06/2019,6.0,Jun,2019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,Small Business,France,Amarilla,High,2475.0,260.0,300.0,742500.0,631125.00,618750.0,12375.00,01/03/2019,3.0,Mar,2019.0
706,Small Business,Mexico,Amarilla,High,546.0,260.0,300.0,163800.0,139230.00,136500.0,2730.00,01/10/2019,10.0,Oct,2019.0
707,Government,Mexico,Montana,High,1368.0,5.0,7.0,9576.0,8139.60,6840.0,1299.60,01/02/2019,2.0,Feb,2019.0
708,Government,Canada,Paseo,High,723.0,10.0,7.0,5061.0,4301.85,3615.0,686.85,01/04/2019,4.0,Apr,2019.0
709,Channel Partners,USA,VTT,High,1806.0,250.0,12.0,21672.0,18421.20,5418.0,13003.20,01/05/2019,5.0,May,2019.0

In [109]:
#To count unique values based on the product column of the dataset

sales_data['Product'].value_counts()

Product
Paseo        203
Velo         110
VTT          110
Carretera     94
Montana       94
Amarilla      94
Name: count, dtype: int64

In [110]:
#To count unique values based on the Segment column

sales_data['Segment'].value_counts()

Segment
Government          302
Small Business      102
Enterprise          101
Midmarket           100
Channel Partners    100
Name: count, dtype: int64

In [97]:
#To count the values in the Segment column as a proportion of the total

sales_data['Segment'].value_counts(normalize=True)

Segment
Government          0.428369
Small Business      0.144681
Enterprise          0.143262
Midmarket           0.141844
Channel Partners    0.141844
Name: proportion, dtype: float64

In [111]:
#To compute the summary statistics of the numerical columns in the dataset

sales_data.describe()

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Sales,COGS,Profit,Month Number,Year
count,705.000000,705.000000,705.000000,7.050000e+02,7.050000e+02,705.000000,705.000000,705.00000,705.000000
mean,1607.514184,96.343262,118.673759,1.829354e+05,1.698758e+05,145680.571631,24195.234270,7.89078,2018.750355
std,865.599524,108.535374,136.732803,2.539818e+05,2.365671e+05,203716.034901,42710.712683,3.38458,0.433115
min,200.000000,3.000000,7.000000,1.799000e+03,1.655080e+03,918.000000,-40617.500000,1.00000,2018.000000
25%,905.000000,5.000000,12.000000,1.740900e+04,1.594098e+04,7554.000000,2906.640000,5.00000,2019.000000
50%,1545.000000,10.000000,20.000000,3.798000e+04,3.587220e+04,22550.000000,9242.600000,9.00000,2019.000000
75%,2222.000000,250.000000,300.000000,2.772000e+05,2.605800e+05,245310.000000,22662.000000,10.00000,2019.000000
max,4492.500000,260.000000,350.000000,1.207500e+06,1.159200e+06,950625.000000,262200.000000,12.00000,2019.000000

In [98]:
#To confirm if there are any missing values per column in the dataset

sales_data.isna().any()

Segment                True
Country                True
Product                True
Discount Band          True
Units Sold             True
Manufacturing Price    True
Sale Price             True
Gross Sales            True
 Sales                 True
COGS                   True
Profit                 True
Date                   True
Month Number           True
Month Name             True
Year                   True
dtype: bool

In [99]:
#To check the total number of missing values per column

sales_data.isna().sum()

Segment                 5
Country                 5
Product                 5
Discount Band          61
Units Sold              5
Manufacturing Price     5
Sale Price              5
Gross Sales             5
 Sales                  5
COGS                    5
Profit                  5
Date                    5
Month Number            5
Month Name              5
Year                    5
dtype: int64

In [106]:
#Missing values threshold

#To calculate for 5% of the values in the column

threshold=(5/100) * len(sales_data)
threshold

35.25

In [ ]:
'''
If number of rows containing missing values <= 5% of the entire rows = DELETE ROWS

COLUMNS WITH NUMERICAL FIGURES
If number of rows containing missing values > 5% of the entire rows = 
                        Replace with the average of the numerical values in the column

COLUMNS WITH TEXT VALUES
If number of rows containing missing values > 5% of the entire rows = 
                        Replace with the most occuring value in the column
'''

In [100]:
#To fill the missing values in the discount column with another value

sales_data.fillna({'Discount Band':'No Discount'},inplace=True)

In [101]:
#To confirm if the missing values were changed

sales_data.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,No Discount,1618.5,3.0,20.0,32370.0,32370.0,16185.0,16185.0,01/01/2019,1.0,Jan,2019.0
1,Government,GERMANY,Carretera,No Discount,1321.0,3.0,20.0,26420.0,26420.0,13210.0,13210.0,01/01/2019,1.0,Jan,2019.0
2,Midmarket,France,Carretera,No Discount,2178.0,3.0,15.0,32670.0,32670.0,21780.0,10890.0,01/06/2019,6.0,Jun,2019.0
3,Midmarket,GERMANY,Carretera,No Discount,888.0,3.0,15.0,13320.0,13320.0,8880.0,4440.0,01/06/2019,6.0,Jun,2019.0
4,Midmarket,Mexico,Carretera,No Discount,2470.0,3.0,15.0,37050.0,37050.0,24700.0,12350.0,01/06/2019,6.0,Jun,2019.0

In [102]:
#To recheck if there are missing values 

sales_data.isna().sum()

Segment                5
Country                5
Product                5
Discount Band          0
Units Sold             5
Manufacturing Price    5
Sale Price             5
Gross Sales            5
 Sales                 5
COGS                   5
Profit                 5
Date                   5
Month Number           5
Month Name             5
Year                   5
dtype: int64

In [103]:
#To eliminate the missing values per column

sales_data.dropna(inplace=True)

#inplace=True is to modify the original dataset imported into the current notebook

In [104]:
#To recheck if there are missing values 

sales_data.isna().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [105]:
len(sales_data)

705